### ISSUE TITLE
grapswiz.com のリニューアル

### ISSUE THREAD

**Issue by watilde** [grapswiz/grapswiz#3]
[ぐらぷす公式サイト](http://grapswiz.com)を、いま流行りの`<marquee>`タグなどを使ってリニューアルしてみる。

**Comment by grapswiz** [comment]
ボドゲしたい気持ちを受け取れるようになうでやんぐな[Push Notification](https://developers.google.com/web/updates/2015/03/push-notificatons-on-the-open-web)を使ってボタンを設置しました
