### ISSUE TITLE
SplatoonのウデマエをA帯にする

### ISSUE THREAD

**Issue by kubosho** [grapswiz/grapswiz#4]

**Comment by vvakame** [comment]
A+に一瞬浮上まではイケるっしょ…！ A+99には壁がある印象。

**Comment by grapswiz** [comment]
B now

**Comment by grapswiz** [comment]
![clgk3mnuwaab_cj](https://cloud.githubusercontent.com/assets/309459/8963925/a841c3be-365d-11e5-908b-169960e7f847.jpg)

**Comment by kubosho** [comment]
:+1:

**Comment by grapswiz** [comment]
![clzomkpucaaowf3](https://cloud.githubusercontent.com/assets/309459/9025952/1e2e35a8-3956-11e5-8885-8dc8608e7303.jpg)

**Comment by axross** [comment]
:+1:

**Comment by armorik83** [comment]
:tada:

**Comment by vvakame** [comment]
:+1:

**Comment by kubosho** [comment]
:+1:

**Comment by grapswiz** [comment]
![couldorucaamksa](https://cloud.githubusercontent.com/assets/309459/9724417/de76750a-5611-11e5-9bae-69ff0f8c3512.jpg)

**Comment by aibou** [comment]
:congratulations: :confetti_ball: :congratulations:

**Comment by vvakame** [comment]
:confetti_ball: :+1:

**Comment by kubosho** [comment]
:tada: :tada: :tada:
